[workspace]
resolver = "2"
members = [
    "crates/message/phone",
    "crates/message/csv",
    "crates/message/ir",
    "crates/message/ir-format",
    "crates/message/reexport",
    "crates/message/mail",
    "crates/message/sbr",
    "crates/message/contacts",
    "crates/message/obfuscate",
    "crates/message/media",
    "crates/message/go-sms-mms",
    "crates/exporters/go-sms-pro-exporter",
    "crates/exporters/sms-backup-restore-exporter",
    "crates/exporters/sms-backup-plus-exporter",
    "crates/exporters/openextract-exporter",
    "crates/exporters/imazing-exporter",
    "crates/exporters/imessage-ir-exporter",
    "crates/exporters/whatsapp-exporter",
    "crates/message-vault-io-core",
    "crates/vault-push",
    "crates/vault-pull",
    "src-tauri",
]
