[workspace]
resolver = "2"
members = [
    "crates/libs/phone",
    "crates/libs/csv",
    "crates/libs/ir",
    "crates/libs/ir-format",
    "crates/libs/reexport",
    "crates/libs/mail",
    "crates/libs/sbr",
    "crates/libs/contacts",
    "crates/libs/obfuscate",
    "crates/libs/media",
    "crates/libs/go-sms-mms",
    "crates/libs/journal",
    "crates/exporters/go-sms-pro-exporter",
    "crates/exporters/sms-backup-restore-exporter",
    "crates/exporters/sms-backup-plus-exporter",
    "crates/exporters/openextract-exporter",
    "crates/exporters/imazing-exporter",
    "crates/exporters/imessage-ir-exporter",
    "crates/exporters/whatsapp-exporter",
    "crates/core/message-vault-io-core",
    "crates/cli/vault-push",
    "crates/cli/vault-pull",
    "crates/cli/dump-cli-docs",
    "crates/vault/demo-seed",
    "crates/vault/server",
    "crates/message-vault-io-gui",
]
exclude = ["src-tauri"]

[workspace.dependencies]
message-ir = { path = "crates/libs/ir" }
contacts = { path = "crates/libs/contacts" }
phone = { path = "crates/libs/phone" }
