use clap::Command;

pub struct PageSpec {
    pub id: &'static str,
    pub title: &'static str,
    pub description: &'static str,
    pub rel_path: &'static str,
}

pub const PAGE_SPECS: &[PageSpec] = &[
    PageSpec {
        id: "imessage-ir-exporter",
        title: "iPhone backup (imessage-ir-exporter)",
        description: "Command-line options for exporting Apple Messages from an iPhone backup or chat database.",
        rel_path: "cli/imessage-ir-exporter.md",
    },
    PageSpec {
        id: "sms-backup-restore-exporter",
        title: "SMS Backup & Restore",
        description: "Command-line options for converting an SMS Backup & Restore XML file.",
        rel_path: "cli/sms-backup-restore-exporter.md",
    },
    PageSpec {
        id: "whatsapp-exporter",
        title: "WhatsApp",
        description: "Command-line options for extracting and converting Apple or Android WhatsApp backups.",
        rel_path: "cli/whatsapp-exporter.md",
    },
    PageSpec {
        id: "go-sms-pro-exporter",
        title: "GO SMS Pro",
        description: "Command-line options for rescuing messages from a GO SMS Pro XML export.",
        rel_path: "cli/go-sms-pro-exporter.md",
    },
    PageSpec {
        id: "imazing-exporter",
        title: "iMazing",
        description: "Command-line options for rescuing messages from an iMazing CSV export.",
        rel_path: "cli/imazing-exporter.md",
    },
    PageSpec {
        id: "openextract-exporter",
        title: "OpenExtract",
        description: "Command-line options for rescuing messages from an OpenExtract export.",
        rel_path: "cli/openextract-exporter.md",
    },
    PageSpec {
        id: "sms-backup-plus-exporter",
        title: "SMS Backup+",
        description: "Command-line options for rescuing messages from an SMS Backup+ mail archive.",
        rel_path: "cli/sms-backup-plus-exporter.md",
    },
    PageSpec {
        id: "message-reexporter",
        title: "Convert an existing export",
        description: "Command-line options for converting a Message Vault output directory to another format.",
        rel_path: "cli/message-reexporter.md",
    },
    PageSpec {
        id: "vault-push",
        title: "Push to Message Vault",
        description: "Command-line options for importing a JSONL export folder into Message Vault.",
        rel_path: "cli/vault-push.md",
    },
    PageSpec {
        id: "vault-pull",
        title: "Pull from Message Vault",
        description: "Command-line options for downloading messages from Message Vault into a local JSONL folder.",
        rel_path: "cli/vault-pull.md",
    },
    PageSpec {
        id: "message-vault-server",
        title: "Vault server CLI",
        description: "Cargo subcommands for import, dedupe, contacts, demo reset, and serve.",
        rel_path: "server-cli.md",
    },
];

pub fn render_page(spec: &PageSpec, command: &Command) -> String {
    let body = clap_markdown::help_markdown_command(command);
    format!(
        "---\ntitle: {title}\ndescription: {description}\neditUrl: false\n---\n\n<!-- generated by dump-cli-docs; do not edit -->\n\n{body}\n",
        title = spec.title,
        description = spec.description,
        body = body.trim(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::{CommandFactory, Parser};

    #[derive(Parser)]
    #[command(name = "demo-tool", about = "Demo about")]
    struct DemoCli {
        /// Input path
        #[arg(long)]
        input: String,
    }

    #[test]
    fn render_page_has_starlight_frontmatter_and_clap_body() {
        let spec = PageSpec {
            id: "demo-tool",
            title: "Demo title",
            description: "Demo description",
            rel_path: "cli/demo-tool.md",
        };
        let page = render_page(&spec, &DemoCli::command());
        assert!(page.starts_with("---\n"));
        assert!(page.contains("title: Demo title"));
        assert!(page.contains("description: Demo description"));
        assert!(page.contains("editUrl: false"));
        assert!(page.contains("generated by dump-cli-docs; do not edit"));
        assert!(page.contains("--input"));
        assert!(!page.contains("## NAME"));
    }

    #[test]
    fn page_specs_cover_eleven_commands() {
        assert_eq!(PAGE_SPECS.len(), 11);
        let ids: Vec<&str> = PAGE_SPECS.iter().map(|s| s.id).collect();
        assert_eq!(
            ids,
            [
                "imessage-ir-exporter",
                "sms-backup-restore-exporter",
                "whatsapp-exporter",
                "go-sms-pro-exporter",
                "imazing-exporter",
                "openextract-exporter",
                "sms-backup-plus-exporter",
                "message-reexporter",
                "vault-push",
                "vault-pull",
                "message-vault-server",
            ]
        );
        assert_eq!(PAGE_SPECS[10].rel_path, "server-cli.md");
        assert_eq!(PAGE_SPECS[8].rel_path, "cli/vault-push.md");
    }
}
