use clap::Command;

pub struct PageSpec {
    pub id: &'static str,
    pub title: &'static str,
    pub description: &'static str,
    pub rel_path: &'static str,
}

pub const PAGE_SPECS: &[PageSpec] = &[
    PageSpec {
        id: "imessage-ir-exporter",
        title: "iPhone backup (imessage-ir-exporter)",
        description: "Command-line options for exporting Apple Messages from an iPhone backup or chat database.",
        rel_path: "cli/imessage-ir-exporter.md",
    },
    PageSpec {
        id: "sms-backup-restore-exporter",
        title: "SMS Backup & Restore",
        description: "Command-line options for converting an SMS Backup & Restore XML file.",
        rel_path: "cli/sms-backup-restore-exporter.md",
    },
    PageSpec {
        id: "whatsapp-exporter",
        title: "WhatsApp",
        description: "Command-line options for extracting and converting Apple or Android WhatsApp backups.",
        rel_path: "cli/whatsapp-exporter.md",
    },
    PageSpec {
        id: "go-sms-pro-exporter",
        title: "GO SMS Pro",
        description: "Command-line options for rescuing messages from a GO SMS Pro XML export.",
        rel_path: "cli/go-sms-pro-exporter.md",
    },
    PageSpec {
        id: "imazing-exporter",
        title: "iMazing",
        description: "Command-line options for rescuing messages from an iMazing CSV export.",
        rel_path: "cli/imazing-exporter.md",
    },
    PageSpec {
        id: "openextract-exporter",
        title: "OpenExtract",
        description: "Command-line options for rescuing messages from an OpenExtract export.",
        rel_path: "cli/openextract-exporter.md",
    },
    PageSpec {
        id: "sms-backup-plus-exporter",
        title: "SMS Backup+",
        description: "Command-line options for rescuing messages from an SMS Backup+ mail archive.",
        rel_path: "cli/sms-backup-plus-exporter.md",
    },
    PageSpec {
        id: "message-reexporter",
        title: "Convert an existing export",
        description: "Command-line options for converting a Message Vault output directory to another format.",
        rel_path: "cli/message-reexporter.md",
    },
    PageSpec {
        id: "vault-push",
        title: "Push to Message Vault",
        description: "Command-line options for importing a JSONL export folder into Message Vault.",
        rel_path: "cli/vault-push.md",
    },
    PageSpec {
        id: "vault-pull",
        title: "Pull from Message Vault",
        description: "Command-line options for downloading messages from Message Vault into a local JSONL folder.",
        rel_path: "cli/vault-pull.md",
    },
    PageSpec {
        id: "message-vault-server",
        title: "Vault server CLI",
        description: "Cargo subcommands for import, dedupe, contacts, demo reset, and serve.",
        rel_path: "server-cli.md",
    },
];

pub fn render_page(spec: &PageSpec, command: &Command) -> String {
    let body = clap_markdown::help_markdown_command(command);
    format!(
        "---\ntitle: {title}\ndescription: {description}\neditUrl: false\n---\n\n<!-- generated by dump-cli-docs; do not edit -->\n\n{body}\n",
        title = spec.title,
        description = spec.description,
        body = body.trim(),
    )
}

pub fn command_for(id: &str) -> anyhow::Result<clap::Command> {
    Ok(match id {
        "imessage-ir-exporter" => imessage_ir_exporter::clap_command(),
        "sms-backup-restore-exporter" => sms_backup_restore_exporter::clap_command(),
        "whatsapp-exporter" => whatsapp_exporter::clap_command(),
        "go-sms-pro-exporter" => go_sms_pro_exporter::clap_command(),
        "imazing-exporter" => imazing_exporter::clap_command(),
        "openextract-exporter" => openextract_exporter::clap_command(),
        "sms-backup-plus-exporter" => sms_backup_plus_exporter::clap_command(),
        "message-reexporter" => message_reexport::clap_command(),
        "vault-push" => vault_push::clap_command(),
        "vault-pull" => vault_pull::clap_command(),
        "message-vault-server" => message_vault_server::clap_command(),
        other => anyhow::bail!("unknown command id {other}"),
    })
}

pub fn page_markdown(id: &str) -> anyhow::Result<String> {
    let spec = PAGE_SPECS
        .iter()
        .find(|s| s.id == id)
        .ok_or_else(|| anyhow::anyhow!("unknown page id {id}"))?;
    Ok(render_page(spec, &command_for(id)?))
}

pub fn write_pages(output_dir: &std::path::Path) -> anyhow::Result<()> {
    for spec in PAGE_SPECS {
        let path = output_dir.join(spec.rel_path);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&path, page_markdown(spec.id)?)?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::{CommandFactory, Parser};
    use std::path::PathBuf;

    #[derive(Parser)]
    #[command(name = "demo-tool", about = "Demo about")]
    struct DemoCli {
        /// Input path
        #[arg(long)]
        input: String,
    }

    #[test]
    fn render_page_has_starlight_frontmatter_and_clap_body() {
        let spec = PageSpec {
            id: "demo-tool",
            title: "Demo title",
            description: "Demo description",
            rel_path: "cli/demo-tool.md",
        };
        let page = render_page(&spec, &DemoCli::command());
        assert!(page.starts_with("---\n"));
        assert!(page.contains("title: Demo title"));
        assert!(page.contains("description: Demo description"));
        assert!(page.contains("editUrl: false"));
        assert!(page.contains("generated by dump-cli-docs; do not edit"));
        assert!(page.contains("--input"));
        assert!(!page.contains("## NAME"));
    }

    #[test]
    fn page_specs_cover_eleven_commands() {
        assert_eq!(PAGE_SPECS.len(), 11);
        let ids: Vec<&str> = PAGE_SPECS.iter().map(|s| s.id).collect();
        assert_eq!(
            ids,
            [
                "imessage-ir-exporter",
                "sms-backup-restore-exporter",
                "whatsapp-exporter",
                "go-sms-pro-exporter",
                "imazing-exporter",
                "openextract-exporter",
                "sms-backup-plus-exporter",
                "message-reexporter",
                "vault-push",
                "vault-pull",
                "message-vault-server",
            ]
        );
        assert_eq!(PAGE_SPECS[10].rel_path, "server-cli.md");
        assert_eq!(PAGE_SPECS[8].rel_path, "cli/vault-push.md");
    }

    #[test]
    fn committed_cli_pages_match_dump() {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../..");
        let output_dir = root.join("docs/src/content/docs/vault/developer/reference");
        for spec in PAGE_SPECS {
            let dumped = page_markdown(spec.id).unwrap();
            let committed = std::fs::read_to_string(output_dir.join(spec.rel_path)).unwrap();
            assert_eq!(
                dumped, committed,
                "run: cargo run -p dump-cli-docs -- --output-dir docs/src/content/docs/vault/developer/reference"
            );
        }
    }
}
