//! Human-looking first/last names for obfuscated display names.

pub(crate) const FIRST_NAMES: &[&str] = &[
    "Alex", "Jordan", "Taylor", "Morgan", "Casey", "Riley", "Avery", "Quinn", "Jamie", "Reese",
    "Cameron", "Drew", "Logan", "Parker", "Sawyer", "Emerson", "Finley", "Harper", "Hayden",
    "Jesse", "Kendall", "Lane", "Micah", "Noah", "Owen", "Peyton", "River", "Rowan", "Sage",
    "Skyler", "Spencer", "Tatum", "Blake", "Charlie", "Dakota", "Eden", "Ellis", "Frankie", "Gray",
    "Harley", "Indigo", "Jules", "Kai", "Lennon", "Marley", "Nico", "Oakley", "Phoenix", "Remy",
    "Sam", "Shawn", "Terry", "Val", "Winter", "Zion", "Adrian", "Bailey", "Chris", "Dana",
    "Elliot", "Francis", "Gale", "Hunter", "Ivan", "Jean", "Kelly", "Lee", "Max", "Nora", "Ollie",
    "Pat", "Robin", "Sidney", "Tracy", "Uma", "Vera", "Wade", "Xander", "Yuki", "Zoe", "Amari",
    "Blair", "Corey", "Devon", "Evan", "Flynn", "Grant", "Hope", "Iris", "Jade", "Kit", "Lou",
    "Milan", "Noel", "Pearl", "Reed", "Shane", "True", "Uri", "Vince", "Wynn", "Yael", "Ari",
    "Brook", "Cruz", "Dell", "Echo", "Fern", "Glen", "Hank", "Ivy", "Joss", "Kris", "Lark", "Moss",
    "Nell", "Ora", "Pace", "Quinn", "Rory", "Shea", "Tess", "Ula", "Vale", "West", "Yves", "Zara",
    "Ada", "Ben", "Cara", "Dean", "Eva", "Finn", "Gina", "Hugo", "Ida", "Joel", "Kara", "Leo",
    "Mia", "Nate", "Olive", "Paul", "Rosa", "Sean", "Tina", "Ugo", "Vito", "Willa", "Xena", "Yara",
    "Zack", "Alice", "Bob", "Clara", "David", "Elena", "Felix", "Grace", "Henry", "Isla", "Jack",
    "Kate", "Liam", "Maya", "Nina", "Oscar", "Paula", "Quinn", "Ruth", "Sara", "Tom", "Una",
    "Victor", "Wendy", "Xavier", "Yvonne", "Zoe", "Andre", "Bella", "Carlo", "Diana", "Ethan",
    "Fiona", "George", "Hannah", "Isaac", "Julia", "Kevin", "Laura", "Marcus", "Nadia", "Omar",
    "Priya",
];

pub(crate) const LAST_NAMES: &[&str] = &[
    "Adams",
    "Baker",
    "Carter",
    "Davis",
    "Edwards",
    "Foster",
    "Garcia",
    "Harris",
    "Iverson",
    "Johnson",
    "Keller",
    "Lopez",
    "Miller",
    "Nguyen",
    "Owens",
    "Patel",
    "Quinn",
    "Rivera",
    "Smith",
    "Turner",
    "Underwood",
    "Vargas",
    "Walker",
    "Xu",
    "Young",
    "Zimmerman",
    "Allen",
    "Brooks",
    "Clark",
    "Diaz",
    "Ellis",
    "Fisher",
    "Green",
    "Hayes",
    "Ingram",
    "Jones",
    "Kim",
    "Lewis",
    "Moore",
    "Nelson",
    "Ortiz",
    "Perez",
    "Reed",
    "Scott",
    "Torres",
    "Uves",
    "Vaughn",
    "White",
    "Yang",
    "Bennett",
    "Cooper",
    "Duncan",
    "Evans",
    "Flores",
    "Graham",
    "Hughes",
    "James",
    "King",
    "Long",
    "Morgan",
    "Nash",
    "Olson",
    "Price",
    "Ross",
    "Stone",
    "Thomas",
    "Vega",
    "Ward",
    "Abbott",
    "Bishop",
    "Cohen",
    "Drake",
    "Eaton",
    "Frank",
    "Grant",
    "Holt",
    "Irwin",
    "Jacobs",
    "Kane",
    "Lane",
    "Marsh",
    "Norris",
    "Page",
    "Quinn",
    "Ryan",
    "Shaw",
    "Tate",
    "Vance",
    "Wells",
    "Yates",
    "Boone",
    "Cross",
    "Dale",
    "Frost",
    "Gibbs",
    "Hart",
    "Ives",
    "Jensen",
    "Knox",
    "Lynch",
    "Mendez",
    "Nolan",
    "Parks",
    "Ramsey",
    "Sloan",
    "Trent",
    "Vogel",
    "Walsh",
    "York",
    "Blair",
    "Chase",
    "Dean",
    "Fox",
    "Glenn",
    "Hale",
    "Ivory",
    "Jules",
    "Kemp",
    "Lowe",
    "Mead",
    "Nye",
    "Pike",
    "Reyes",
    "Sims",
    "Todd",
    "West",
    "Bell",
    "Cole",
    "Dunn",
    "Fry",
    "Gray",
    "Hill",
    "Jack",
    "Kent",
    "Lee",
    "Moss",
    "Noon",
    "Paul",
    "Rice",
    "Snow",
    "Tyler",
    "Webb",
    "Ball",
    "Camp",
    "Dodd",
    "Finn",
    "Gould",
    "Hahn",
    "Inman",
    "Jolly",
    "Kline",
    "Lamb",
    "Mays",
    "Neal",
    "Owen",
    "Pope",
    "Rich",
    "Sand",
    "Thorne",
    "Voss",
    "Wood",
    "Bond",
    "Clay",
    "Duke",
    "Fern",
    "Gage",
    "Hood",
    "Isle",
    "Jade",
    "Keel",
    "Lord",
    "Moon",
    "Nova",
    "Oak",
    "Penn",
    "Rose",
    "Star",
    "Vale",
];
