//! Derive the Postgres DDL from the SQLite originals in `schema/sql/`.
//!
//! The two dialects differ by four mechanical rules, so the Postgres variant
//! is transpiled from the SQLite source at first use instead of being
//! hand-maintained as a parallel set of files:
//!
//! 1. `INTEGER PRIMARY KEY` becomes a `BIGINT` identity column.
//! 2. `DEFAULT (datetime('now'))` becomes the same `YYYY-MM-DD HH:MM:SS`
//!    UTC string via `to_char` (see `dialect::group_concat`'s neighbours for
//!    the query-side twin).
//! 3. `UNIQUE COLLATE NOCASE` has no Postgres twin: the column loses the
//!    inline constraint and a `lower(column)` expression index takes over.
//! 4. Postgres validates `REFERENCES` targets at DDL time, so a foreign key
//!    to a table created by a later DDL file is stripped inline and re-added
//!    afterwards as an idempotent `ALTER TABLE` block.
//!
//! Anything structurally different between the engines (full-text search)
//! stays hand-written in its own `schema/sql/fts_postgres*.sql` files.

/// Transpiled Postgres DDL: one entry per SQLite source, in application
/// order, plus the deferred foreign keys to run after all of them.
pub(crate) struct PgDdl {
    /// Postgres DDL per source file, same order as the input.
    pub files: Vec<String>,
    /// Idempotent `ALTER TABLE ... ADD CONSTRAINT` blocks for foreign keys
    /// whose target table is created by a later file. Empty string when the
    /// sources have none.
    pub deferred_fks: String,
}

/// Postgres twin of SQLite's `DEFAULT (datetime('now'))`.
const PG_NOW_UTC: &str = "(to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))";

/// A foreign key stripped from a column because its target table did not
/// exist yet at that point of the DDL sequence.
struct DeferredFk {
    table: String,
    column: String,
    clause: String,
}

/// Transpile the SQLite DDL files (in application order) to Postgres.
pub(crate) fn transpile(sources: &[&str]) -> PgDdl {
    let mut created: Vec<String> = Vec::new();
    let mut deferred: Vec<DeferredFk> = Vec::new();
    let files = sources
        .iter()
        .map(|source| transpile_file(source, &mut created, &mut deferred))
        .collect();
    PgDdl {
        files,
        deferred_fks: render_deferred_fks(&deferred),
    }
}

fn transpile_file(
    source: &str,
    created: &mut Vec<String>,
    deferred: &mut Vec<DeferredFk>,
) -> String {
    let mut out = String::with_capacity(source.len());
    let mut pending_ci: Vec<(String, String)> = Vec::new();
    let mut current_table = String::new();

    for line in source.lines() {
        let mut line = line.to_string();

        if let Some(rest) = line
            .trim_start()
            .strip_prefix("CREATE TABLE IF NOT EXISTS ")
        {
            current_table = table_name(rest);
            created.push(current_table.clone());
        }

        line = line.replace(
            "INTEGER PRIMARY KEY",
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        );
        line = line.replace(
            "DEFAULT (datetime('now'))",
            &format!("DEFAULT {PG_NOW_UTC}"),
        );

        if line.contains(" UNIQUE COLLATE NOCASE") {
            let column = column_name(&line);
            line = line.replace(" UNIQUE COLLATE NOCASE", "");
            pending_ci.push((current_table.clone(), column));
        }

        if let Some(idx) = line.find(" REFERENCES ") {
            let target = table_name(&line[idx + " REFERENCES ".len()..]);
            if !created.contains(&target) {
                let clause_end = line.rfind(',').unwrap_or(line.len());
                deferred.push(DeferredFk {
                    table: current_table.clone(),
                    column: column_name(&line),
                    clause: line[idx + 1..clause_end].to_string(),
                });
                line.replace_range(idx..clause_end, "");
            }
        }

        out.push_str(&line);
        out.push('\n');

        // A table just closed: its case-insensitive indexes come right after.
        if line.trim() == ");" {
            for (table, column) in pending_ci.drain(..) {
                out.push_str(&format!(
                    "-- Case-insensitive uniqueness (SQLite's UNIQUE COLLATE NOCASE twin).\n\
                     CREATE UNIQUE INDEX IF NOT EXISTS ix_{table}_{column}_ci ON {table} (lower({column}));\n"
                ));
            }
        }
    }
    out
}

/// First identifier of a `CREATE TABLE`/`REFERENCES` tail: the table name.
fn table_name(rest: &str) -> String {
    rest.trim_start()
        .split(|c: char| c.is_whitespace() || c == '(' || c == ';')
        .next()
        .unwrap_or_default()
        .to_string()
}

/// First identifier on a column-definition line: the column name.
fn column_name(line: &str) -> String {
    line.trim_start()
        .split_whitespace()
        .next()
        .unwrap_or_default()
        .to_string()
}

/// Render deferred foreign keys as idempotent `DO $$` blocks (a plain
/// `ADD CONSTRAINT` would fail the second time `ensure_vault_schema` runs).
fn render_deferred_fks(fks: &[DeferredFk]) -> String {
    let mut out = String::new();
    for fk in fks {
        let DeferredFk {
            table,
            column,
            clause,
        } = fk;
        out.push_str(&format!(
            "DO $$\n\
             BEGIN\n\
             {i}IF NOT EXISTS (\n\
             {i}{i}SELECT 1 FROM pg_constraint WHERE conname = '{table}_{column}_fkey'\n\
             {i}) THEN\n\
             {i}{i}ALTER TABLE {table}\n\
             {i}{i}{i}ADD CONSTRAINT {table}_{column}_fkey\n\
             {i}{i}{i}FOREIGN KEY ({column}) {clause};\n\
             {i}END IF;\n\
             END $$;\n",
            i = "    "
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    const PARENT: &str = "\
-- The parent table.
CREATE TABLE IF NOT EXISTS parents (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE COLLATE NOCASE,
    forward_id INTEGER NOT NULL REFERENCES laters(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
";

    const LATER: &str = "\
CREATE TABLE IF NOT EXISTS laters (
    id INTEGER PRIMARY KEY,
    parent_id INTEGER NOT NULL REFERENCES parents(id) ON DELETE CASCADE
);
";

    #[test]
    fn integer_primary_keys_become_identities() {
        let ddl = transpile(&[PARENT, LATER]);
        for file in &ddl.files {
            assert!(!file.contains("INTEGER PRIMARY KEY"), "{file}");
        }
        assert!(ddl.files[0].contains("id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"));
    }

    #[test]
    fn datetime_now_defaults_become_utc_to_char() {
        let ddl = transpile(&[PARENT]);
        assert!(!ddl.files[0].contains("datetime('now')"));
        assert!(ddl.files[0].contains(&format!("DEFAULT {PG_NOW_UTC}")));
    }

    #[test]
    fn nocase_unique_moves_to_a_lower_index() {
        let ddl = transpile(&[PARENT]);
        let file = &ddl.files[0];
        assert!(file.contains("    name TEXT NOT NULL,\n"));
        assert!(file.contains(
            "CREATE UNIQUE INDEX IF NOT EXISTS ix_parents_name_ci ON parents (lower(name));"
        ));
    }

    #[test]
    fn forward_references_are_deferred_and_backward_ones_kept() {
        let ddl = transpile(&[PARENT, LATER]);
        // The forward FK (parents -> laters) leaves the column line…
        assert!(ddl.files[0].contains("    forward_id INTEGER NOT NULL,\n"));
        // …and comes back as an idempotent ALTER TABLE afterwards.
        assert!(
            ddl.deferred_fks
                .contains("conname = 'parents_forward_id_fkey'")
        );
        assert!(
            ddl.deferred_fks
                .contains("FOREIGN KEY (forward_id) REFERENCES laters(id) ON DELETE CASCADE;")
        );
        // The backward FK (laters -> parents) stays inline.
        assert!(
            ddl.files[1]
                .contains("parent_id INTEGER NOT NULL REFERENCES parents(id) ON DELETE CASCADE")
        );
    }
}
